### PR TITLE
Raise the memory alarm to 80%

### PR DESCRIPTION
**Pull request by bdero**
This settings addition sets the high memory alarm to 80%. The default is 40%.

CC @smarnach

### CODE REVIEW

**Review by smarnach — COMMENTED** [review]
@bdero Can you please make this configurable, just in case we have to change it again?  The default of 0.8 should be fine for all servers, since they are all dedicated RabbitMQ machines.  (And seriously, who came up with this configuration file syntax?)

**Comment by bdero** [comment]
@smarnach Yup good idea, I added a var for it.

Yeah, it's technically [valid erlang](http://erlang.org/doc/man/config.html), but the spacing conventions are really difficult to follow. I've been contemplating not following the conventions and just spacing it in a reasonable way instead.

**Comment by smarnach** [comment]
@bdero Looks good to me now.  Will you have time to deploy this to rabbitmq-stage?  We don't need to deploy to all servers, just to the stage server for testing.  In production, I fixed it manually, so it should be fine until we redeploy.

:+1:

**Comment by smarnach** [comment]
@bdero I will actually merge this first, since it makes deployment easier.  If I find a problem, I'll roll back.

**Comment by smarnach** [comment]
I've deployed this to the stage server, and everything is looking fine.  I verified the configuration file, and checked the highwatermark in the admin web interface.

**Pull request merged**
